### ISSUE TITLE
Generated services throw error 500

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-security-client10#20]
Following error is thrown when trying to retrieve the Capabilities of a generated service:

```
HTTP ERROR 500 java.lang.IncompatibleClassChangeError: Found interface org.opengis.cite.jetty.http.pathmap.PathSpec, but class was expected
...
Caused by:

java.lang.IncompatibleClassChangeError: Found interface org.opengis.cite.jetty.http.pathmap.PathSpec, but class was expected
	at org.opengis.cite.jetty.servlet.ServletHandler.doScope(ServletHandler.java:455)
	at org.opengis.cite.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.opengis.cite.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.opengis.cite.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.opengis.cite.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.opengis.cite.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.opengis.cite.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.opengis.cite.jetty.server.Server.handle(Server.java:516)
	at org.opengis.cite.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.opengis.cite.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.opengis.cite.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.opengis.cite.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.opengis.cite.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.opengis.cite.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.opengis.cite.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
	at org.opengis.cite.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
	at org.opengis.cite.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.opengis.cite.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.opengis.cite.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.opengis.cite.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.opengis.cite.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.opengis.cite.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.opengis.cite.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.opengis.cite.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.opengis.cite.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

The test suite was started with Docker by executing `mvn clean install docker:run -Pdocker`.

**Comment by keshav-nangare** [comment]
@dstenger 
I am able to reproduce the reported behavior. The `jetty-server` dependency updated to a newer version but `jetty-servlet` dependency having an older version. I updated the version and able to get a response of Capabilities generated service.

Please find the changes in #21 PR.
